### ISSUE TITLE
Interop tests not failing fast

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1575]
Sometimes in CI an interop test times out.  Whatever is started in the test is not torn down so the CI build doesn't fail, instead hangs until GH actions kill it which takes six hours.

For example - https://github.com/libp2p/js-libp2p/actions/runs/4064646740/jobs/6998407028

```
  dht.contentRouting
    1) "before all" hook for "js peer to go peer"


  17 passing (43s)
  1 failing

  1) dht.contentRouting
       "before all" hook for "js peer to go peer":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/js-libp2p/js-libp2p/dist/test/interop.js)
      at listOnTimeout (node:internal/timers:564:17)
      at processTimers (node:internal/timers:507:7)
```

Here it's a 'before all' hook that's timing out - this should cause the test runner to exit immediately so it'll be a case of tracking down what's still running and ensure it gets torn down when there's an error.

**Comment by ckousik** [comment]
@achingbrain I've seen a similar issue where a TCP listener is not closing causing the tests to hang.
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
  - fd 0 (tty)
- Servers:
  - 127.0.0.1:42261 (TCP)
    - Listeners:
      - connection: bound onSocket @ file:///home/ckousik/projects/js-libp2p/node_modules/@libp2p/tcp/src/listener.ts:78
- Timers:
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
  - (60000 ~ 60 s) (anonymous) @ unknown:0
  - (1000 ~ 1000 ms) (anonymous) @ file:///home/ckousik/projects/js-libp2p/test/interop.ts:204

```
(NOTE: The timer is for debug)

As a temporary solution, should we force the interop tests to exit from the CLI?
